# ORRRG - Self-Organizing Core Configuration
# ==========================================

system:
  name: "ORRRG - Omnipotent Research and Reasoning Reactive Grid"
  version: "1.0.0"
  log_level: "INFO"
  max_concurrent_tasks: 10
  heartbeat_interval: 30  # seconds

components:
  # Academic Publishing and Workflow Automation
  oj7s3:
    enabled: true
    priority: 8
    resource_allocation:
      cpu_limit: 2
      memory_limit: "4GB"
    interfaces:
      - web_api
      - agent_coordination
    dependencies:
      - mysql
      - php
      - nodejs

  # Interactive Compiler Exploration
  echopiler:
    enabled: true
    priority: 7
    resource_allocation:
      cpu_limit: 2
      memory_limit: "2GB"
    interfaces:
      - web_api
      - compilation_service
    dependencies:
      - nodejs
      - docker

  # OpenCog Cognitive Architecture
  oc-skintwin:
    enabled: true
    priority: 9
    resource_allocation:
      cpu_limit: 4
      memory_limit: "8GB"
    interfaces:
      - atomspace_api
      - reasoning_engine
    dependencies:
      - opencog
      - guile
      - python

  # Protein/Language Model Hypergraph Analysis
  esm-2-keras-esm2_t6_8m-v1-hyper-dev2:
    enabled: true
    priority: 8
    resource_allocation:
      cpu_limit: 4
      memory_limit: "16GB"
      gpu_enabled: true
    interfaces:
      - model_inference
      - hypergraph_analysis
    dependencies:
      - pytorch
      - transformers
      - tensorflow

  # Genomic and Proteomic Research
  cosmagi-bio:
    enabled: true
    priority: 7
    resource_allocation:
      cpu_limit: 2
      memory_limit: "4GB"
    interfaces:
      - bioinformatics_api
      - opencog_bio
    dependencies:
      - opencog
      - bioinformatics_tools

  # Chemical Information Processing
  coscheminformatics:
    enabled: true
    priority: 6
    resource_allocation:
      cpu_limit: 1
      memory_limit: "2GB"
    interfaces:
      - chemical_analysis
    dependencies:
      - cmake
      - rdkit

  # ONNX Runtime for ML Inference
  echonnxruntime:
    enabled: true
    priority: 8
    resource_allocation:
      cpu_limit: 2
      memory_limit: "4GB"
      gpu_enabled: true
    interfaces:
      - ml_inference
      - onnx_optimization
    dependencies:
      - onnx
      - cuda

  # Chemical Reasoning System
  coschemreasoner:
    enabled: true
    priority: 7
    resource_allocation:
      cpu_limit: 2
      memory_limit: "4GB"
    interfaces:
      - chemical_reasoning
      - reaction_prediction
    dependencies:
      - python
      - scikit-learn

# Integration patterns define how components work together
integration_patterns:
  bio_chemical_pipeline:
    description: "Integrated biological and chemical analysis"
    components:
      - cosmagi-bio
      - coscheminformatics
      - coschemreasoner
    data_flow:
      - source: cosmagi-bio
        target: coscheminformatics
        transform: "genomic_to_chemical"
      - source: coscheminformatics
        target: coschemreasoner
        transform: "chemical_data_to_reasoning"

  ml_inference_pipeline:
    description: "Machine learning model inference and optimization"
    components:
      - esm-2-keras-esm2_t6_8m-v1-hyper-dev2
      - echonnxruntime
    data_flow:
      - source: esm-2-keras-esm2_t6_8m-v1-hyper-dev2
        target: echonnxruntime
        transform: "model_to_onnx"

  research_publication_pipeline:
    description: "Research analysis to publication workflow"
    components:
      - cosmagi-bio
      - coscheminformatics
      - coschemreasoner
      - oj7s3
    data_flow:
      - source: [cosmagi-bio, coscheminformatics, coschemreasoner]
        target: oj7s3
        transform: "research_to_manuscript"

  cognitive_reasoning_pipeline:
    description: "Cognitive modeling and reasoning integration"
    components:
      - oc-skintwin
      - coschemreasoner
      - esm-2-keras-esm2_t6_8m-v1-hyper-dev2
    data_flow:
      - source: [coschemreasoner, esm-2-keras-esm2_t6_8m-v1-hyper-dev2]
        target: oc-skintwin
        transform: "domain_knowledge_to_atomspace"

# Self-organization parameters
self_organization:
  adaptation_enabled: true
  learning_rate: 0.01
  optimization_interval: 300  # seconds
  performance_metrics:
    - component_utilization
    - response_time
    - throughput
    - error_rate
  
  auto_scaling:
    enabled: true
    scale_up_threshold: 0.8
    scale_down_threshold: 0.3
    min_instances: 1
    max_instances: 5

# Knowledge graph configuration
knowledge_graph:
  storage_backend: "networkx"  # Options: networkx, neo4j, atomspace
  auto_discovery: true
  relationship_inference: true
  
  ontologies:
    - chemistry
    - biology
    - machine_learning
    - software_engineering
    - cognitive_science

# API and interface configuration
api:
  host: "0.0.0.0"
  port: 8000
  cors_enabled: true
  authentication: false  # Set to true for production
  rate_limiting:
    enabled: true
    requests_per_minute: 100

# Monitoring and observability
monitoring:
  metrics_enabled: true
  metrics_port: 9090
  health_check_endpoint: "/health"
  performance_tracking: true
  
  alerts:
    - condition: "cpu_usage > 90%"
      action: "scale_up"
    - condition: "memory_usage > 85%"
      action: "optimize_memory"
    - condition: "error_rate > 5%"
      action: "notify_admin"

# Security configuration
security:
  encryption_enabled: false  # Enable for production
  secure_communication: false  # Enable for production
  access_control: false  # Enable for production
  audit_logging: true